[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = false
optimizer = true
optimizer_runs = 1000000
verbosity = 1
solc_version = "0.8.22"

[rpc_endpoints]
ethereum-mainnet = "${ETHEREUM_MAINNET_RPC_URL}"
arbitrum-mainnet = "${ARBITRUM_MAINNET_RPC_URL}"
base-mainnet = "${BASE_MAINNET_RPC_URL}"
optimism-mainnet = "${OPTIMISM_MAINNET_RPC_URL}"
polygon-mainnet = "${POLYGON_MAINNET_RPC_URL}"
avalanche-mainnet = "${AVALANCHE_MAINNET_RPC_URL}"
bsc-mainnet = "${BSC_MAINNET_RPC_URL}"



